align_assignment = true
align_conditional = true
align_matrix = true
align_pair_arrow = true
align_struct_field = true
always_for_in = true
always_use_return = true
annotate_untyped_fields_with_any = true
conditional_to_if = false
for_in_replacement = "in"
format_docstrings = true
import_to_using = true
indent = 4
indent_submodule = false
join_lines_based_on_source = true
long_to_short_function_def = false
margin = 32767
normalize_line_endings = "unix"
pipe_to_function_call = false
remove_extra_newlines = false
separate_kwargs_with_semicolon = true
short_circuit_to_if = false
short_to_long_function_def = false
surround_whereop_typeparameters = true
trailing_comma = true
trailing_zero = true
variable_call_indent = []
whitespace_in_kwargs = true
whitespace_ops_in_indices = false
whitespace_typedefs = true
